apiVersion: v2
name: spark-operator
description: A Helm chart for Spark on Kubernetes operator
version: 1.4.1
appVersion: v1beta2-1.6.0-3.5.0
keywords:
  - spark
home: https://github.com/kubeflow/spark-operator
maintainers:
  - name: yuchaoran2011
    email: yuchaoran2011@gmail.com
