run:
  deadline: 5m

linters:
  enable:
  - revive
  - gci
  - depguard
  - godot
  - testifylint
  - unconvert

issues:
  exclude-rules:
  # Disable errcheck linter for test files.
  - path: _test.go
    linters:
    - errcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kubeflow/spark-operator)
  depguard:
    Main:
      files:
        - $all
        - "!$test"
      listMode: Lax
      deny:
        reflect: Please don't use reflect package
    Test:
      files:
        - $test
      listMode: Lax
      deny:
        reflect: Please don't use reflect package
