name: 'Release Action'
description: 'Build and Push the application docker image'

inputs:
    aws-role-to-assume:
      description: 'AWS Role to Assume'
      required: true
    public-registry-id:
      description: 'Public ECR Registry ID'
      required: true

runs:
  using: "composite"
  steps:
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-session-name: ${{ inputs.aws-role-session-name }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws

    - name: Build images
      run: make -f .github/actions/release/Makefile build
      shell: bash
      env:
        REGISTRY: public.ecr.aws/${{ inputs.public-registry-id }}/

    - name: Push images
      run: make -f .github/actions/release/Makefile push
      shell: bash
      env:
        BRANCH: ${{ steps.branch-name.outputs.current_branch }}
        REGISTRY: public.ecr.aws/${{ inputs.public-registry-id }}/

    - name: Display exported images
      run: make -f .github/actions/release/Makefile show
      shell: bash
      env:
        BRANCH: ${{ steps.branch-name.outputs.current_branch }}
        REGISTRY: public.ecr.aws/${{ inputs.public-registry-id }}/
