name: 'Release Action'
description: 'Build and Push the application docker image'

inputs:
    aws-access-key-id:
      description: 'AWS Access Key ID'
      required: true
    aws-secret-access-key:
      description: 'AWS Secret Access Key'
      required: true
    public-registry-id:
      description: 'Public ECR Registry ID'
      required: true

runs:
  using: "composite"
  steps:
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ inputs.aws-access-key-id }}
        password: ${{ inputs.aws-secret-access-key }}

    - name: Build AMD64 images
      run: make -f .github/ocean-spark/Makefile build
      shell: bash
      env:
        BRANCH: ${{ steps.branch-name.outputs.current_branch }}
        REGISTRY: public.ecr.aws/${{ inputs.public-registry-id }}/
        PLATFORM: amd64

    - name: Push AMD64 images
      run: make -f .github/ocean-spark/Makefile push
      shell: bash
      env:
        BRANCH: ${{ steps.branch-name.outputs.current_branch }}
        REGISTRY: public.ecr.aws/${{ inputs.public-registry-id }}/
        PLATFORM: amd64

    - name: Build ARM64 images
      run: make -f .github/ocean-spark/Makefile build
      shell: bash
      env:
        BRANCH: ${{ steps.branch-name.outputs.current_branch }}
        REGISTRY: public.ecr.aws/${{ inputs.public-registry-id }}/
        PLATFORM: arm64

    - name: Push ARM64 images
      run: make -f .github/ocean-spark/Makefile push
      shell: bash
      env:
        BRANCH: ${{ steps.branch-name.outputs.current_branch }}
        REGISTRY: public.ecr.aws/${{ inputs.public-registry-id }}/
        PLATFORM: arm64

    - name: Push manifest
      run: make -f .github/ocean-spark/Makefile push-manifest
      shell: bash
      env:
        BRANCH: ${{ steps.branch-name.outputs.current_branch }}
        REGISTRY: public.ecr.aws/${{ inputs.public-registry-id }}/
