name: Trivy Image Scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'


jobs:
  internal-ecr-trivy:
    name: Trivy Scan for Internal ECR
    uses: spotinst/bigdata-infrastructure/.github/workflows/ofas-trivy-scan.yaml@main
    with:
      image: spark-operator
      tag: ocean-spark
      aws-ecr-url: public.ecr.aws/ocean-spark
      send-slack-notification-on-failure: true
      create-jira-ticket: false
    secrets:
      slack-notification-webhook: ${{ secrets.SLACK_DEVOPS_CHANNEL_WEBHOOK }}